Upgrade terraform version to 0.12.17
This is because apply pipeline needs to use this version.

Error: state snapshot was created by Terraform v0.12.17, which is newer than current v0.12.13; upgrade to Terraform v0.12.17 or greater to work with this state